Invoke-WebRequest 'https://raw.githubusercontent.com/HHEELLPP/Windows11Tweaks/refs/heads/master/utils.psm1'|Invoke-Expression

if(Test-CommandExists pwsh.exe -Invert) {
	winget.exe install --id Microsoft.PowerShell --source winget --scope user --exact --accept-source-agreements --accept-package-agreements
}

if($PSVersionTable.PSEdition -ne 'Core') {
	'PowerShell'
	$aaaa = {
		Invoke-WebRequest 'https://raw.githubusercontent.com/HHEELLPP/Windows11Tweaks/refs/heads/master/plsWork.ps1' | Invoke-Expression
	}
	pwsh.exe -NoExit -Command $aaaa 
 	exit
} else {
	'pwsh'
}

New-Item -Path 'U:\themes' -ItemType 'directory' -Force
New-Item -Path 'U:\themes\wallpapers' -ItemType 'directory' -Force
if((Test-Path -LiteralPath "$env:SystemRoot\web\wallpaper\Windows\img19.jpg" -PathType 'Leaf')-and((Test-Path -LiteralPath 'U:\themes\wallpapers\img19.jpg' -PathType 'Leaf')-ne$true)){Copy-Item -Path "$env:SystemRoot\web\wallpaper\Windows\img19.jpg" -Destination 'U:\themes\wallpapers\img19.jpg'}
$Result=@{
	'HKEY_CURRENT_USER\Control Panel\Desktop'=@{
		'TileWallpaper'=@{
			'Value'='0'
			'PropertyType'='String'
		}
		'WallpaperOriginX'=@{
			'Value'=0
			'PropertyType'='DWord'
		}
		'WallpaperOriginY'=@{
			'Value'=0
			'PropertyType'='DWord'
		}
		'WallpaperStyle'=@{
			'Value'='10'
			'PropertyType'='String'
		}
		'WindowArrangementActive'=@{
			'Value'='1'
			'PropertyType'='String'
		}
		'WallPaper'=@{
			'Value'='U:\themes\wallpapers\img19.jpg'
			'PropertyType'='String'
		}
		'AutoColorization'=@{
			'Value'=0
			'PropertyType'='DWord'
		}
	}
	'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Accent'=@{
		'AccentPalette'=@{
			'Value'=[byte[]](0xec,0xc6,0xf7,0x00,0xd2,0xa5,0xed,0x00,0xa6,0x6a,0xdc,0x00,0x95,0x54,0xd5,0x00,0x74,0x31,0xc9,0x00,0x4e,0x25,0x99,0x00,0x21,0x0f,0x6a,0x00,0x88,0x17,0x98,0x00)
			'PropertyType'='Binary'
		}
		'StartColorMenu'=@{
			'Value'=-3591820
			'PropertyType'='DWord'
		}
		'AccentColorMenu'=@{
			'Value'=-2796395
			'PropertyType'='DWord'
		}
	}
	'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced'=@{
		'DontPrettyPath'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'Hidden'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'HideDrivesWithNoMedia'=@{
			'Value'=0
			'PropertyType'='DWord'
		}
		'HideFileExt'=@{
			'Value'=0
			'PropertyType'='DWord'
		}
		'NavPaneExpandToCurrentFolder'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'NavPaneShowAllFolders'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'SeparateProcess'=@{
			'Value'=0
			'PropertyType'='DWord'
		}
		'ServerAdminUI'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'ShowSecondsInSystemClock'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'ShowSuperHidden'=@{
			'Value'=0
			'PropertyType'='DWord'
		}
		'ShowSyncProviderNotifications'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'TaskbarAl'=@{
			'Value'=0
			'PropertyType'='DWord'
		}
	}
	'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes'=@{
		'ThemeChangesDesktopIcons'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'ThemeChangesMousePointers'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'WallpaperSetFromTheme'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'ColorSetFromTheme'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'CurrentTheme'=@{
			'Value'='C:\Windows\resources\Themes\dark.theme'
			'PropertyType'='String'
		}
		'ThemeMRU'=@{
			'Value'='C:\Windows\resources\Themes\dark.theme;C:\Windows\resources\Themes\aero.theme;'
			'PropertyType'='String'
		}
	}
	'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize'=@{
		'ColorPrevalence'=@{
			'Value'=0
			'PropertyType'='DWord'
		}
		'EnableTransparency'=@{
			'Value'=0
			'PropertyType'='DWord'
		}
		'AppsUseLightTheme'=@{
			'Value'=0
			'PropertyType'='DWord'
		}
		'SystemUsesLightTheme'=@{
			'Value'=0
			'PropertyType'='DWord'
		}
		'ThemeChangesDesktopIcons'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'ThemeChangesMousePointers'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'WallpaperSetFromTheme'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
	}
	'HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM'=@{
		'Composition'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'ColorizationColor'=@{
			'Value'=-998293313
			'PropertyType'='DWord'
		}
		'ColorizationColorBalance'=@{
			'Value'=89
			'PropertyType'='DWord'
		}
		'ColorizationAfterglow'=@{
			'Value'=-998293313
			'PropertyType'='DWord'
		}
		'ColorizationAfterglowBalance'=@{
			'Value'=10
			'PropertyType'='DWord'
		}
		'ColorizationBlurBalance'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'EnableWindowColorization'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'ColorizationGlassAttribute'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'AccentColor'=@{
			'Value'=-4243329
			'PropertyType'='DWord'
		}
		'ColorPrevalence'=@{
			'Value'=0
			'PropertyType'='DWord'
		}
		'EnableAeroPeek'=@{
			'Value'=1
			'PropertyType'='DWord'
		}
		'UseDpiScaling'=@{
			'Value'=0
			'PropertyType'='DWord'
		}
	}
	"HKEY_USERS\$([System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value)\Control Panel\International"=@{
		'iMeasure'=@{
			'Value'='1'
			'PropertyType'='String'
		}
		's1159'=@{
			'Value'='AM'
			'PropertyType'='String'
		}
		'sNegativeSign'=@{
			'Value'='-'
			'PropertyType'='String'
		}
		'iNegCurr'=@{
			'Value'='0'
			'PropertyType'='String'
		}
		'sGrouping'=@{
			'Value'='3;0'
			'PropertyType'='String'
		}
		'LocaleName'=@{
			'Value'='en-US'
			'PropertyType'='String'
		}
		'NumShape'=@{
			'Value'='1'
			'PropertyType'='String'
		}
		'sMonDecimalSep'=@{
			'Value'='.'
			'PropertyType'='String'
		}
		'iCalendarType'=@{
			'Value'='1'
			'PropertyType'='String'
		}
		'sDate'=@{
			'Value'='-'
			'PropertyType'='String'
		}
		'sTimeFormat'=@{
			'Value'='HH:mm:ss'
			'PropertyType'='String'
		}
		'sList'=@{
			'Value'=','
			'PropertyType'='String'
		}
		's2359'=@{
			'Value'='PM'
			'PropertyType'='String'
		}
		'iFirstDayOfWeek'=@{
			'Value'='0'
			'PropertyType'='String'
		}
		'iDate'=@{
			'Value'='2'
			'PropertyType'='String'
		}
		'sLanguage'=@{
			'Value'='ENU'
			'PropertyType'='String'
		}
		'sShortDate'=@{
			'Value'='yyyy-MM-dd'
			'PropertyType'='String'
		}
		'sLongDate'=@{
			'Value'='yyyy MMMM d dddd'
			'PropertyType'='String'
		}
		'sTime'=@{
			'Value'=':'
			'PropertyType'='String'
		}
		'iPaperSize'=@{
			'Value'='1'
			'PropertyType'='String'
		}
		'iDigits'=@{
			'Value'='2'
			'PropertyType'='String'
		}
		'iCountry'=@{
			'Value'='1'
			'PropertyType'='String'
		}
		'sCurrency'=@{
			'Value'='$'
			'PropertyType'='String'
		}
		'sMonGrouping'=@{
			'Value'='3;0'
			'PropertyType'='String'
		}
		'iTLZero'=@{
			'Value'='0'
			'PropertyType'='String'
		}
		'sYearMonth'=@{
			'Value'='yyyy MMMM'
			'PropertyType'='String'
		}
		'iTimePrefix'=@{
			'Value'='0'
			'PropertyType'='String'
		}
		'sMonThousandSep'=@{
			'Value'=','
			'PropertyType'='String'
		}
		'iCurrDigits'=@{
			'Value'='2'
			'PropertyType'='String'
		}
		'sShortTime'=@{
			'Value'='HH:mm'
			'PropertyType'='String'
		}
		'sDecimal'=@{
			'Value'='.'
			'PropertyType'='String'
		}
		'sThousand'=@{
			'Value'=','
			'PropertyType'='String'
		}
		'iCurrency'=@{
			'Value'='0'
			'PropertyType'='String'
		}
		'Locale'=@{
			'Value'='00000409'
			'PropertyType'='String'
		}
		'iNegNumber'=@{
			'Value'='1'
			'PropertyType'='String'
		}
		'iLZero'=@{
			'Value'='1'
			'PropertyType'='String'
		}
		'iFirstWeekOfYear'=@{
			'Value'='0'
			'PropertyType'='String'
		}
		'sPositiveSign'=@{
			'Value'=''
			'PropertyType'='String'
		}
		'sNativeDigits'=@{
			'Value'='0123456789'
			'PropertyType'='String'
		}
		'iTime'=@{
			'Value'='0'
			'PropertyType'='String'
		}
	}
}
taskkill /f /im explorer.exe 2>&1> $null
try {
	foreach($LiteralPath in $Result.Keys) {
		foreach($Name in $Result.$LiteralPath.Keys) {
			$Result.$LiteralPath.$Name
			if((Test-Path -LiteralPath "Registry::$LiteralPath") -ne $true){New-Item $LiteralPath -Force}
			New-ItemProperty -LiteralPath "Registry::$LiteralPath" -Name $Name -Value $Result.$LiteralPath.$Name.Value -PropertyType $Result.$LiteralPath.$Name.PropertyType -Force
		}
	}
} finally {Start-Process explorer.exe}

Get-CimInstance Win32_OperatingSystem | Select-Object -Property 'Caption','OSArchitecture' | Format-List

Stop-Program
